---
mechanism: oauth_2
scope: https://www.googleapis.com/auth/calendar
client_id: 666890685093-dd5llu08ej3t4j6ljfrqfvgmno708bqp.apps.googleusercontent.com
client_secret: 4TDJy-Ac7nZCVfaLEiz9H2Eo
access_token: ya29.Ci8tA2WG9a-AUthj-Ybnfx4nuGBeaApr8QPd58ey7afBsIUSxWXBbig6QXGukZ0FpA
refresh_token: 1/TyfLhyXSJqCq_yNUDdxXLAeIY84qY8M7xZcXBKVtwEY
